# -*- coding: utf-8 -*-

#:import main main


<MainForm>


	#:set INPUT_H 32 * 2
	#:set INPUT_W INPUT_H * 3


##	#:import main main
##	#:set INPUT_H main.INPUT_H
##	#:set INPUT_W main.INPUT_W



    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        padding: 5
        spacing: 1

        Label:
            id: label1
            text: "Please Write Your Name Here"
            # font_size: 32
            size_hint_y: 0.5


        # https://kivy.org/doc/stable/api-kivy.uix.textinput.html
        TextInput:
            id: input1
            multiline: False
            pos_hint: {"center_x": 0.5}
            size_hint: (None, None)
            width: INPUT_W
            height: INPUT_H
            ##
            halign: 'right'
            input_filter: 'int'
            ##
            on_text_validate: root.InputEnter()

        TextInput:
            id: input2
            multiline: False
            pos_hint: {"center_x": 0.5}
            size_hint: (None, None)
            width: INPUT_W
            height: INPUT_H
            ##
            halign: 'right'
            input_filter: 'int'
            ##
            on_text_validate: root.InputEnter()

        TextInput:
            id: input3
            multiline: False
            pos_hint: {"center_x": 0.5}
            size_hint: (None, None)
            width: INPUT_W
            height: INPUT_H
            ##
            halign: 'right'
            input_filter: 'int'
            ##
            on_text_validate: root.InputEnter()




        Label:
            id: label2
            text: ""
            # font_size: 32
            pos_hint: {"center_x": 0.5}
            size_hint_y: 0.5

        Label:
            id: label3
            text: ""
            # font_size: 32
            pos_hint: {"center_x": 0.5}
            size_hint_y: 0.5


        Button:
            size_hint: (1, .5)
            # font_size: 32
            text: "Enter"
            pos_hint: {"center_x": 0.5}
            size_hint: (None, None)
            width: 200
            height: 50
            on_press: root.ButtonPress()

        Button:
            size_hint: (1, .5)
            # font_size: 32
            text: "Test Exec"
            pos_hint: {"center_x": 0.5}
            size_hint: (None, None)
            width: 200
            height: 50
            on_press: root.ButtonTestPress()
